version: "3.2"

services:
  mongo:
    image: mongo
    container_name: "mongodb"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1q2w3e4r
    command: "mongod --auth"
    expose:
      - 27017 # only containers
    #ports:
    #  - 27017:27017 # expose outside (on host)

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./services/db/.env.mongo

  api:
    build: ./services/web/app
    expose:
      - 8080 # only containers
    #ports:
    #  - 8080:8080
    depends_on:
      - mongo

  react:
    build: ./services/react
    depends_on:
      - mongo
    ports:
      - 80:80
