version: "3.7"

services:
  mongo:
    image: mongo
    container_name: "mongodb"
    restart: always
    env_file: ./services/db/.env
    volumes:
      - mongov:/data/db
    expose:
      - 27017 # only containers

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file: ./services/db/express.env
    depends_on:
      - mongo

  api:
    build: ./services/web/app
    expose:
      - 8080 # only containers
    env_file: ./services/web/app/.env
    depends_on:
      - mongo

  react:
    build: ./services/react
    depends_on:
      - api
    ports:
      - 80:80

volumes:
  mongov:
    name: mongov
